# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: vionetaos-app-management
before:
  hooks:
  - go generate
  - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
  - go mod tidy
  # - go test -race -v ./... -timeout 30m
builds:
- id: vionetaos-app-management-amd64
  binary: build/sysroot/usr/bin/vionetaos-app-management
  hooks:
    post:
    - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Vioneta/VionetaOS-AppManagement/cmd/appfile2compose
      output: true
    - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
      output: true
    - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
      output: true
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: vionetaos-app-management-arm64
  binary: build/sysroot/usr/bin/vionetaos-app-management
  hooks:
    post:
    - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Vioneta/VionetaOS-AppManagement/cmd/appfile2compose
      output: true
      # - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
      #   output: true
      # - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
      #   output: true
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: vionetaos-app-management-arm-7
  binary: build/sysroot/usr/bin/vionetaos-app-management
  hooks:
    post:
    - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/Vioneta/VionetaOS-AppManagement/cmd/appfile2compose
      output: true
    - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
      output: true
    - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
      output: true
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
- id: vionetaos-app-management-migration-tool-amd64
  binary: build/sysroot/usr/bin/vionetaos-app-management-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: vionetaos-app-management-migration-tool-arm64
  binary: build/sysroot/usr/bin/vionetaos-app-management-migration-tool
  # hooks:
  #   post:
  #     - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: vionetaos-app-management-migration-tool-arm-7
  binary: build/sysroot/usr/bin/vionetaos-app-management-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
- id: vionetaos-app-management-validator-amd64
  binary: build/sysroot/usr/bin/vionetaos-app-management-validator
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/validator
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64

archives:
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
  id: vionetaos-app-management
  builds:
  - vionetaos-app-management-amd64
  - vionetaos-app-management-arm64
  - vionetaos-app-management-arm-7
  files:
  - build/**/*
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
  id: vionetaos-app-management-migration-tool
  builds:
  - vionetaos-app-management-migration-tool-amd64
  - vionetaos-app-management-migration-tool-arm64
  - vionetaos-app-management-migration-tool-arm-7
  files:
  - build/sysroot/etc/**/*
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-validator-v{{ .Version }}
  id: vionetaos-app-management-validator
  builds:
  - vionetaos-app-management-validator-amd64
  files:
  - build/sysroot/etc/**/*

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
release:
  github:
    owner: Vioneta
    name: VionetaOS-AppManagement
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
